name: Go
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:14-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: tory
          POSTGRES_USER: tory
          POSTGRES_PASSWORD: tory
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - run: go build -v ./...
    - run: go test -v ./...
